# Generated by Django 4.0.3 on 2022-04-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='image_database/default.png', upload_to='image_database/', verbose_name='image'),
        ),
    ]
