# Generated by Django 4.0.3 on 2022-04-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='static/images/default.png', upload_to='image_database/', verbose_name='image'),
        ),
    ]
