# Generated by Django 4.0.3 on 2022-04-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_picture_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
    ]
