# Generated by Django 4.0.3 on 2022-04-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_picture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='gallery',
        ),
        migrations.AddField(
            model_name='picture',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.gallery'),
        ),
    ]
