# Generated by Django 4.0.3 on 2022-04-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_picture_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='image'),
        ),
    ]
